### PR TITLE
Multi Monitor Support

### PR DESCRIPTION
**Pull request by HarveyHunt**
Keeping this in its own branch is getting annoying - it also has some nice fixups that ```develop``` will benefit from.

Testing needs to be done on XRandR setups - I've noticed a segfault that I will look into soon. Single monitor seems to just work (tm).

Relevant discussion can be seen at #5

### CODE REVIEW

**Comment by Anachron** [comment]
What setup of xrandr has this been tested in?

**Comment by HarveyHunt** [comment]
@Anachron: I tested it on a laptop with a monitor plugged in. There were some rendering issues and windows didn't want to spawn on the second monitor, so this PR isn't done yet - I thought it would be good to put the code out for review / issue reporting.

**Comment by HarveyHunt** [comment]
Most of the multi monitor stuff is now done. I still need to add the ability to move a client to a different workspace and also add a motion for a monitor. I also removed some code from ```op_cut```, so that needs to be put back.

However, it should be okay to test - let me know how it goes @Anachron.

**Comment by Anachron** [comment]
@HarveyHunt do you mind if I test in a VM first? Those result may be inaccurate, but I'm messing around with my Arch install for now and cannot use more construction places :+1:

**Comment by HarveyHunt** [comment]
Test it however you fancy. Btw, there is a new function for focusing monitors:

```cottage -f focus_monitor 0```

**Comment by Anachron** [comment]
Wow, a lot of stuff happening here! I forgot that I wanted to test this. :+1:

**Pull request merged**
